// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxgjROCjhYa1XmBYaeIZ5WvUzVOqztIVg',
    appId: '1:256228458394:web:cd74619283916d53b0c423',
    messagingSenderId: '256228458394',
    projectId: 'teaching-f6ae2',
    authDomain: 'teaching-f6ae2.firebaseapp.com',
    storageBucket: 'teaching-f6ae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPutgqEORmN7nsvyO5PrM5tM5qvAVTHt8',
    appId: '1:256228458394:android:0cbb79c9f9fa9c26b0c423',
    messagingSenderId: '256228458394',
    projectId: 'teaching-f6ae2',
    storageBucket: 'teaching-f6ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCur0_BiMYWyeKNz_PBFTuW4SxSMxj2re4',
    appId: '1:256228458394:ios:75db91e41f9a161cb0c423',
    messagingSenderId: '256228458394',
    projectId: 'teaching-f6ae2',
    storageBucket: 'teaching-f6ae2.appspot.com',
    iosBundleId: 'com.example.flutterTeaching',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCur0_BiMYWyeKNz_PBFTuW4SxSMxj2re4',
    appId: '1:256228458394:ios:9ca06e77e21f3904b0c423',
    messagingSenderId: '256228458394',
    projectId: 'teaching-f6ae2',
    storageBucket: 'teaching-f6ae2.appspot.com',
    iosBundleId: 'com.example.flutterTeaching.RunnerTests',
  );
}
